### ISSUE TITLE
Scraping Spotify playlists

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#298]
https://open.spotify.com/browse/featured

This page features periodically updated playlists that could be cool to include in the dashboard in a new tab or in the charts tab. For this purpose we're gonna need a scraper that could be written as a separate module really (maybe using cheerio). The covers and the track lists for each playlist can be easily accessed after figuring out some obfuscated css. The core of this feature should be a scraper that given an url to a playlist returns its title, cover art, and a list of tracks. From that, we can look up streams like we do with everything else.

I'm planning to do this at some point in the future, but if any contributors would like to handle that, you're more than welcome.

**Comment by charjac** [comment]
i can work on this in a few days, (need to finish the equalizer pr).

**Comment by nukeop** [comment]
Sure, if it sounds interesting to you. It's gonna be a side project, really. Meanwhile, I'm probably gonna take on the playlist sharing service, once I finish the "collection" feature.

**Comment by charjac** [comment]
Is this intended to be run in browser or node environment ?

**Comment by nukeop** [comment]
We can do it either way, since it's electron. So do it however it's easier for you.

**Comment by charjac** [comment]
Do you have an "interface" or a "schema" representing what this api should return ?

**Comment by nukeop** [comment]
No, this is not yet represented in nuclear in any way. Although I suppose you could make these similar to internal nuclear playlists for maximum compatibility. We could also use descriptions, and type of the playlist (automatically generated, curated, or created by user). When I make the service for sharing playlists, I'll try to make it compatible with what you're coding. Either way it's not going to be hard to translate the formats in the worst case.

**Comment by charjac** [comment]
I have created a repo https://github.com/charjac/spotify-playlist and add you as collaborator.
 
just clone, install and npm start

For now i just achieve to get something like this:
```js
const playlist = {
  name: '',
  cover:  'pl.scdn.co/images/pl/default/37121bdc9bfebc6bc415f81a9088c695a4f6029a',
  tracks: [ {
    name: 'Flat Beat - Radio Edit',
    artist: { name: '' },
    album: { name: '' }
  }]
} 
```

looks like its a react app and the missing fields are added on the dom via javascript.
If its true, cheerio will not be enough, we will need to use something like https://github.com/GoogleChrome/puppeteer.
The huge drawback of using puppeteer is that it need a chromium / chrome to be installed on the user's computer in order to work ................ :'( :'(. 
So to make it simple it would work but at a huge price.

we could also imagine a webservice wich expose a dead simple api and does the puppeteer job.

**Comment by nukeop** [comment]
Couldn't we just open an invisible electron window (in nuclear), render the page there, and scrape the html, then kill the window? The overhead wouldn't be that big since we're already running Chromium.

**Comment by charjac** [comment]
Ok i found a way, they were storing json from their api in a script tag at the bottom of the html file, so the lib is able to to the job even without cheerio.

I published this npm package: spotify-featured-playlist

here is what the api return:
[playlist.zip](https://github.com/nukeop/nuclear/files/3030579/playlist.zip)

**Comment by nukeop** [comment]
Fantastic news. I'll try to include this in nuclear today or tomorrow. As a side effect, you're building an awesome code portfolio for yourself.

Btw, I can't find your package on npm (by name and on your profile), check if it really did go through.

**Comment by charjac** [comment]
you were right something failed on travis. its fixed now.
https://www.npmjs.com/package/spotify-featured-playlist

**Comment by nukeop** [comment]
How do I use this? I naively tried doing something like this:

```javascript

import SpotifyPlaylist from 'spotify-featured-playlist';

SpotifyPlaylist().then(console.log);
```

But this gives me a TypeError:

```
Uncaught TypeError: Cannot set property 'playlistsPage' of undefined
    at SpotifyPlaylist (spotify-playlist.es5.js:184)
```

**Comment by charjac** [comment]
oops i completely forgot to document it. I am a typescript user and with typescript there is auto completion everywhere <3 (even in js with ts lib) so no need for docs.
wich IDE do you use ? this one is just perfect: https://github.com/VSCodium/vscodium (they kick microsoft shit out of the app :D)

you have to do something like this

```js
import SpotifyPlaylist from 'spotify-featured-playlist';

const foo = new SpotifyPlaylist();

foo.get()
  .then(console.log)
  .catch(console.error);

```

**Comment by nukeop** [comment]
Ok now it's sending a request, and I'm getting a response, but I still can't retrieve the full data. It fails with this:

```
Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at PlaylistsPage.<anonymous> (spotify-playlist.es5.js:102)
    at step (spotify-playlist.es5.js:63)
    at Object.next (spotify-playlist.es5.js:44)
    at fulfilled (spotify-playlist.es5.js:34)
```

Can we also access arbitrary playlists? I can see that there's a method for that but is it exposed?

**Comment by charjac** [comment]
Oops sorry for that, look like someone forgot a try catch somewhere :D.
I will fix this later, add some log for future debugging and add a way to get a single playlist, its not exposed actually.

**Comment by charjac** [comment]
ok it still works here ... maybe they use different data based on localization ?
Could you send me what you get when you GET https://open.spotify.com/browse/featured

**Comment by charjac** [comment]
it break here

```ts
  protected async getSpotifyEntityJSON<T>(): Promise<T> {
    if (!this.markup) {
      await this.fetchMarkup();
    }
    return JSON.parse(
      this.markup
        .split('Spotify.Entity = ')[1]
        .split('</script>')[0]
        .replace(';', ''),
    ) as T;
  }
```

**Comment by charjac** [comment]
I check via Tor and i was right they dont serve same html for every country.
with a french ip a have a script tag with all the json at the bottom.
with tor i get the us version ans this script tag is missing .......... :'(

**Comment by nukeop** [comment]
Well, I'm in Europe too, but it seems that this won't work for all users. Many of them are from USA. This is a hard problem, Spotify doesn't want anyone to get their playlists the easy way. Actually if you want their playlists on your website they only let you use their widget as an embed.

**Comment by nukeop** [comment]
We have a tool now: https://github.com/HaiDang666/extract-sptf-playlist
