### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by abacao** [nukeop/nuclear#384]
## 1. Playlist Management
[https://imgur.com/UPviHGn](https://imgur.com/UPviHGn)

## 2. Favorite Playlists
Please add a favorite playlist in Collection and probably a star next to the playlist title
[https://imgur.com/mC5m8dL](https://imgur.com/mC5m8dL)
Also, consider a way to manage these playlists especially when the feature "shared playlists" is enabled.

## 3. Download queue
Add option to download a entire queue.

## 5. Minimal "always on top" player
A very small window like the bottom bar with just 3 elements: icon, music name, controls (previous, play/pause/next)

**Comment by nukeop** [comment]
Last suggestion is already a feature proposal: https://github.com/nukeop/nuclear/issues/325

What do you mean by queue width? Both panels can be collapsed, would you like to have more control over their size?

**Comment by abacao** [comment]
Go to your favourite desktop file explorer. Between the tree panel on the left (with folders) and the panel on the right with files and folders, you have a division that you can resize at will.

**Comment by nukeop** [comment]
Ok, that is a good suggestion. Any item from your list or even parts of these items (except for the mini player) fall under the "good first issue" tag if anyone wants to take that.

**Comment by zelol** [comment]
Is it ok if I take it?

I got this error when launching the server with `npm run electron:dev`:
```
> nuclear@0.5.0 electron:dev /home/seb/Dev/mynuclear
> webpack --progress --colors --config=webpack.config.electron.js && electron ./bundle.electron.js

Happy[jsx]: Version: 5.0.1. Threads: 3
Happy[jsx]: All set; signaling webpack to proceed.
Hash: 1c41b1f586f1bddfc14d                                                              
Version: webpack 4.35.2
Time: 5166ms
Built at: 04/07/2019 15:33:14
             Asset      Size  Chunks             Chunk Names
bundle.electron.js  9.15 MiB    main  [emitted]  main
Entrypoint main = bundle.electron.js
[./app/constants/settings.js] 4.1 KiB {main} [built]
[./app/rest/youtube-search.js] 466 bytes {main} [built]
[./server/downloads.js] 2.76 KiB {main} [built]
[./server/http/api/index.js] 2.23 KiB {main} [built]
[./server/http/lib/swagger.js] 3.85 KiB {main} [built]
[./server/http/middlewares.js] 1.07 KiB {main} [built]
[./server/http/server.js] 2.27 KiB {main} [built]
[./server/main.dev.js] 5.64 KiB {main} [built]
[./server/store.js] 1.46 KiB {main} [built]
[electron] external "electron" 42 bytes {main} [built]
[fs] external "fs" 42 bytes {main} [built]
[net] external "net" 42 bytes {main} [built]
[path] external "path" 42 bytes {main} [built]
[perf_hooks] external "perf_hooks" 42 bytes {main} [built]
[url] external "url" 42 bytes {main} [built]
    + 1469 hidden modules

WARNING in ./node_modules/conf/node_modules/write-file-atomic/index.js
Module not found: Error: Can't resolve 'worker_threads' in '/home/seb/Dev/mynuclear/node_modules/conf/node_modules/write-file-atomic'
 @ ./node_modules/conf/node_modules/write-file-atomic/index.js
 @ ./node_modules/conf/index.js
 @ ./node_modules/electron-store/index.js
 @ ./server/store.js
 @ ./server/main.dev.js

ERROR in ./app/containers/HttpApiUrl/styles.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import '../../mixin.scss';
| @import '../../vars.scss';
| 
 @ ./app/containers/HttpApiUrl/index.js 21:14-38
 @ ./app/constants/settings.js
 @ ./server/store.js
 @ ./server/main.dev.js

npm ERR! Linux 4.15.0-54-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "electron:dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! nuclear@0.5.0 electron:dev: `webpack --progress --colors --config=webpack.config.electron.js && electron ./bundle.electron.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the nuclear@0.5.0 electron:dev script 'webpack --progress --colors --config=webpack.config.electron.js && electron ./bundle.electron.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nuclear package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --colors --config=webpack.config.electron.js && electron ./bundle.electron.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nuclear
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nuclear
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/seb/Dev/mynuclear/npm-debug.log
```

Do you guys have an idea? @nukeop

**Comment by nukeop** [comment]
Yes, I broke the build yesterday somehow. Something related to the way scss files are loaded. I'll fix it today when I have some free time.

**Comment by nukeop** [comment]
Ok, I think I fixed it now. It required a small refactor.

**Comment by zelol** [comment]
I merged the PR but got exactly the same problems. Can't resolve "worker_threads" from module "write-file-atomic". And "Module parse failed: Unexpected character '@'" inside style.scss.

**Comment by nukeop** [comment]
It's on master, and travis builds it. Don't worry about the worker threads warning.

**Comment by zelol** [comment]
Okay for the worker_threads. The module parsing error still here when typing command `npm run electron:dev` that's weird, maybe cause I'm on Ubuntu... I don't know.

**Comment by nukeop** [comment]
The OS doesn't matter, I use linux too. Travis builds on Ubuntu too.

Clone the repo anew, install dependencies, and try again. If Travis could build it and I could build it, it's got to work. Make sure you have the newest master branch commit. If it still doesn't work, paste the log here and we'll see what's wrong with it.

**Comment by zelol** [comment]
Where is located the log? Sorry, this is all new to me, I'm a newb ^^

**Comment by nukeop** [comment]
This is the same issue as this one:
https://github.com/nukeop/nuclear/pull/342#issuecomment-507325046

**Comment by nukeop** [comment]
Looks like this appears if the config is empty. I'll try to fix this now.

**Comment by nukeop** [comment]
Ok, it's fixed now. You should be able to run it.

**Comment by zelol** [comment]
Okay got some other issues with npm etc.. I think I'll leave it now for somebody else.  I should have fix it before starting to contribute to any project, sorry.

**Comment by nukeop** [comment]
If you have any other problems you can let me know if you think I'll be able to help you, it's not an issue.

**Comment by schippas** [comment]
Is anyone here working on the mini-player from #325? I've been thinking of trying to implement it.

**Comment by nukeop** [comment]
@schippas Feel free to take it if you want!
